apiVersion: v1
kind: Secret
metadata: 
  name: core-env
type: Opaque
data:
    OKTA_URL: aHR0cHM6Ly9hdG9zY2VzLWRldi5va3RhLmNvbQ==
    OKTA_API_TOKEN: MDBPUjJMNGFmNkR1MHNSckVuQlFpaXpGN3FCbW9GTTNkX0IzbVd4NG8x
    DB_HOST: Y29ja3JvYWNoZGItcHVibGlj
    DB_DRIVER: cG9zdGdyZXM=
    DB_USER: cm9vdA==
    DB_PASSWORD: IiI=
    DB_NAME: ZGVmYXVsdGRi
    DB_PORT: MjYyNTc=
